/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as RecipesIndexImport } from "./routes/recipes/index";
import { Route as RecipesRecipeIdImport } from "./routes/recipes/$recipeId";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const RecipesIndexRoute = RecipesIndexImport.update({
  path: "/recipes/",
  getParentRoute: () => rootRoute,
} as any);

const RecipesRecipeIdRoute = RecipesRecipeIdImport.update({
  path: "/recipes/$recipeId",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/recipes/$recipeId": {
      id: "/recipes/$recipeId";
      path: "/recipes/$recipeId";
      fullPath: "/recipes/$recipeId";
      preLoaderRoute: typeof RecipesRecipeIdImport;
      parentRoute: typeof rootRoute;
    };
    "/recipes/": {
      id: "/recipes/";
      path: "/recipes";
      fullPath: "/recipes";
      preLoaderRoute: typeof RecipesIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  RecipesRecipeIdRoute,
  RecipesIndexRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/recipes/$recipeId",
        "/recipes/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/recipes/$recipeId": {
      "filePath": "recipes/$recipeId.tsx"
    },
    "/recipes/": {
      "filePath": "recipes/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
